;;;; tween.import.scm - GENERATED BY CHICKEN 4.8.0 -*- Scheme -*-

(eval '(import scheme chicken))
(##sys#register-compiled-module
  'tween
  (list)
  '((bounce-ease . tween#bounce-ease)
    (back-ease . tween#back-ease)
    (elastic-ease . tween#elastic-ease)
    (circular-ease . tween#circular-ease)
    (exponential-ease . tween#exponential-ease)
    (sinusoidal-ease . tween#sinusoidal-ease)
    (quintic-ease . tween#quintic-ease)
    (quartic-ease . tween#quartic-ease)
    (cubic-ease . tween#cubic-ease)
    (quadratic-ease . tween#quadratic-ease)
    (linear-ease . tween#linear-ease)
    (catmullrom-select . tween#catmullrom-select)
    (bezier-select . tween#bezier-select)
    (linear-select . tween#linear-select)
    (interpolate . tween#interpolate)
    (tween . tween#tween)
    (factorial . tween#factorial)
    (factorial* . tween#factorial*))
  (list)
  (list))

;; END OF FILE
